### ISSUE TITLE
Entering the settings values causes cursor focus to move and reload notification

### ISSUE THREAD

**Issue by johnpapa** [microsoft/docs-scaffolding#45] opened 2021-03-31 17:13 UTC
Every time I type in the github id field or the microsoft alias field, the cursor jumps to the template field, and this dialog appears.

![image](https://user-images.githubusercontent.com/1202528/113184168-db41d480-9222-11eb-961f-b516238f4619.png)

**Comment by jamarw** [comment] 2021-04-02 15:45
Hi @johnpapa, VS Code will save the settings as you type but the setting will not be applied until the editor is reloaded. We added an event handler to detect this change and prompt users to reload so the changes are reflected properly.

I tried to repro the cursor issue but unfortunately I was not able to reproduce the behavior. Would you mind providing additional repro steps or a short video capture so we can repro the issue and get a fix in?

Thanks!

**Comment by johnpapa** [comment] 2021-04-02 16:08
I'll take a video of it and share here. It prompted me to reload like 7 times and kept moving the cursor.

It seems interesting that changing settings would cause a reload. Perhaps we can trigger the extension to apply the changes without a reload (I do this in Peacock, for example)

**Comment by jamarw** [comment] 2021-04-02 16:12
Great and thanks for the info! I'll check it out to see if we can mimic what you've done in the extension.

**Comment by johnpapa** [comment] 2021-04-02 16:28
Great ... did you see my question on reloading?

> It seems interesting that changing settings would cause a reload. Perhaps we can trigger the extension to apply the changes without a reload (I do this in Peacock, for example).

**Comment by johnpapa** [comment] 2021-04-02 16:29
The cursor is not moving now. but I have a feeling the reload events are what is causing it.

![2021-04-02_12-25-22 (1)](https://user-images.githubusercontent.com/1202528/113434475-0a854c80-93af-11eb-83db-e65116cac137.gif)

**Comment by jamarw** [comment] 2021-04-02 17:05
> Great ... did you see my question on reloading?
> 
> > It seems interesting that changing settings would cause a reload. Perhaps we can trigger the extension to apply the changes without a reload (I do this in Peacock, for example).

Yes and we should definitely be able to improve that experience. I'm looking into a fix now.

**Comment by jamarw** [comment] 2021-04-06 19:42
https://github.com/microsoft/docs-scaffolding/pull/50

**Comment by jamarw** [comment] 2021-07-20 20:23
Fixed in PR https://github.com/microsoft/docs-scaffolding/pull/50

**Closed by jamarw** 2021-07-20 20:23 UTC
